const data = [
  {
    Name: 'Bret',
    Email: 'Sincere@april.biz',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Leanne Graham',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Antonette',
    Email: 'Shanna@melissa.tv',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Ervin Howell',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Samantha',
    Email: 'Nathan@yesenia.net',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Clementine Bauch',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Karianne',
    Email: 'Julianne.OConner@kory.org',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Patricia Lebsack',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Kamren',
    Email: 'Lucio_Hettinger@annie.ca',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Chelsey Dietrich',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Leopoldo_Corkery',
    Email: 'Karley_Dach@jasper.info',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Mrs. Dennis Schulist',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Elwyn.Skiles',
    Email: 'Telly.Hoeger@billy.biz',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Kurtis Weissnat',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Maxime_Nienow',
    Email: 'Sherwood@rosamond.me',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Nicholas Runolfsdottir V',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Delphine',
    Email: 'Chaim_McDermott@dana.io',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Glenna Reichert',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
  {
    Name: 'Moriah.Stanton',
    Email: 'Rey.Padberg@karina.biz',
    Date: '12.11.2022',
    "Visit Time": '12:46:55',
    Doctor: 'Clementina DuBuque',
    Condition: 'Dead Inside',
    Avatar: 'https://web.damirlut.online/ninja/cards/10120_m.png',
  },
];

export default data;
